package server;

import org.apache.activemq.ActiveMQConnectionFactory;
import org.omg.CORBA.ORB;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;
import javax.imageio.ImageIO;
import javax.jms.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.PrintWriter;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import common.ComputeService;
import common.ImageChunk;
import common.ProcessedChunk;
import CorbaModule.*;
import java.util.concurrent.LinkedBlockingQueue;


public class HospitalServer extends UnicastRemoteObject implements ComputeService {

    // 1. DATA STRUCTURES
    private LinkedBlockingQueue<ImageChunk> tasks = new LinkedBlockingQueue<>();
    private int totalChunks = 40;

    // 2. CONSTRUCTOR and IMAGE LOADING
    public HospitalServer() throws Exception {
        super();
        loadImageAndSplit("server/src/main/resources/hand-xray.jpg");
    }

    private void loadImageAndSplit(String path) throws Exception {
        File imgFile = new File(path);
        if (!imgFile.exists()) {
            System.err.println("ERROR: Image not found at " + imgFile.getAbsolutePath());
            return;
        }

        BufferedImage original = ImageIO.read(imgFile);
        int w = original.getWidth();
        int h = original.getHeight();

        System.out.println("Loaded Image: " + w + "x" + h);

        int chunkHeight = h / totalChunks;

        for (int i = 0; i < totalChunks; i++) {
            int y = i * chunkHeight;
            int currentH = (i == totalChunks - 1) ? (h - y) : chunkHeight;
            int[] pixels = original.getRGB(0, y, w, currentH, null, 0, w);
            tasks.add(new ImageChunk(i, 0, y, w, currentH, pixels));
        }
        System.out.println("Image split into " + tasks.size() + " tasks.");
    }

    // 3. RMI IMPLEMENTATION (Worker Logic)

    @Override
    public ImageChunk getTask() {
        return tasks.poll();
    }

    @Override
    public void submitResult(ProcessedChunk result) {
        System.out.println("Received processed chunk ID: " + result.id);
        sendJmsUpdate(result);
    }


    // 4. JMS IMPLEMENTATION (Doctor Logic)

    private void sendJmsUpdate(ProcessedChunk result) {
        try {
            ConnectionFactory factory = new ActiveMQConnectionFactory("tcp://localhost:61616");
            ((ActiveMQConnectionFactory) factory).setTrustAllPackages(true);
            Connection connection = factory.createConnection();
            connection.start();
            Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
            Topic topic = session.createTopic("TeleRadiology");
            MessageProducer producer = session.createProducer(topic);
            ObjectMessage msg = session.createObjectMessage(result);
            producer.send(msg); // Send to Dashboard
            session.close();
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // 5. CORBA INNER CLASS (Admin Logic)

    // This class implements the Interface generated by 'idlj'
    static class MonitorImpl extends CorbaModule.MonitorPOA {
        private final HospitalServer server;

        public MonitorImpl(HospitalServer server) {
            this.server = server;
        }

        @Override
        public String getStatus() {
            int remaining = server.tasks.size();
            return "System Online. Pending Tasks: " + remaining;
        }
    }

    // 6. MAIN METHOD (Entry Point)
    public static void main(String[] args) {
        try {
            ORB orb = ORB.init(args, null);
            POA rootpoa = POAHelper.narrow(orb.resolve_initial_references("RootPOA"));
            rootpoa.the_POAManager().activate();
            HospitalServer hs = new HospitalServer();
            MonitorImpl monitor = new MonitorImpl(hs);
            org.omg.CORBA.Object ref = rootpoa.servant_to_reference(monitor);
            String ior = orb.object_to_string(ref);
            PrintWriter out = new PrintWriter("server.ior");
            out.println(ior);
            out.close();
            System.out.println("CORBA Monitor ready. IOR written to 'server.ior'.");
            Registry registry = LocateRegistry.createRegistry(1099);
            registry.rebind("ComputeService", hs);
            System.out.println("RMI Service Ready on port 1099...");
            new Thread(() -> {
                try {
                    orb.run();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }).start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}